### ISSUE TITLE
Hi，I am very interested in your project. I want to know what the title of the paper corresponding to this project? Look forward to your reply.

### ISSUE THREAD

**Issue by HJW0522** [gc535/LivenessDectectionForFaceSpoofingAttack#1]

**Comment by gc535** [comment]
Thanks. I just included a doc named "paper" in the root dir. I lose track of some papers. Will include later if I found them.

**Comment by gc535** [comment]
Thanks. I just included a doc named "paper" in the root dir. I lose track of some papers. Will include later if I find them.
