### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by olijouve** [gc535/LivenessDectectionForFaceSpoofingAttack#2]
Hi,
First thanks for you work, it's seem promizing.

I encounter an issue trying to compil your code, it fails on the lbpdata part :

$ make
g++ -c -g -o obj/helper.o ShearletUtil/helper.cpp -O0 -std=c++11  -I.  -I./ShearletUtil  -I./QualityUtil/  -I/DATA/opencv_contrib/modules/hdf/include/
ShearletUtil/helper.cpp: In function 'std::vector<std::vector<std::pair<cv::Mat, cv::Mat> > > Shearlet::shearing_filters_Myer(std::vector<int>&, std::vector<int>&, int)':
ShearletUtil/helper.cpp:278:6: error: 'ifft2shift' was not declared in this scope
      ifft2shift(input_real, input_img, ifftshift_real, ifftshift_img);
      ^~~~~~~~~~
ShearletUtil/helper.cpp:278:6: note: suggested alternative: 'ifftshift_img'
      ifft2shift(input_real, input_img, ifftshift_real, ifftshift_img);
      ^~~~~~~~~~
      ifftshift_img
ShearletUtil/helper.cpp:280:6: error: 'ifft2' was not declared in this scope
      ifft2(ifftshift_real, ifftshift_img, ifft2_real, ifft2_img, false);
      ^~~~~
ShearletUtil/helper.cpp:280:6: note: suggested alternative: 'erff32'
      ifft2(ifftshift_real, ifftshift_img, ifft2_real, ifft2_img, false);
      ^~~~~
      erff32
ShearletUtil/helper.cpp:282:6: error: 'fft2shift' was not declared in this scope
      fft2shift(ifft2_real, ifft2_img, fft2_real, fft2_img);
      ^~~~~~~~~
ShearletUtil/helper.cpp:282:6: note: suggested alternative: 'fft2_img'
      fft2shift(ifft2_real, ifft2_img, fft2_real, fft2_img);
      ^~~~~~~~~
      fft2_img
ShearletUtil/helper.cpp:319:13: error: 'fft2' was not declared in this scope
             fft2(shear_real, shear_img, tmp_real, tmp_img, false);
             ^~~~
ShearletUtil/helper.cpp:319:13: note: suggested alternative: 'ffsl'
             fft2(shear_real, shear_img, tmp_real, tmp_img, false);
             ^~~~
             ffsl
Makefile:121: recipe for target 'obj/helper.o' failed
make: *** [obj/helper.o] Error 1

Trying to include shear.hpp in the header.hpp file leads to news errors:
$ make
g++ -o ../bin/lbp obj/lbpExtraction.o obj/Data.o obj/LBP.o obj/Util.o obj/SingleChannelDOG.o obj/ELBP.o obj/lbp_hist.o obj/brisque.o obj/helper.o -O0 -std=c++11  -I.  -I./ShearletUtil  -I./QualityUtil/  -I/DATA/opencv_contrib/modules/hdf/include/ -L/usr/local/lib -lopencv_hdf -lopencv_ml -lopencv_dnn -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_core  
obj/helper.o: In function `Shearlet::shearing_filters_Myer(std::vector<int, std::allocator<int> >&, std::vector<int, std::allocator<int> >&, int)':
/DATA/LivenessDectectionForFaceSpoofingAttack/src/ShearletUtil/helper.cpp:279: undefined reference to `ifft2shift(cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&)'
/DATA/LivenessDectectionForFaceSpoofingAttack/src/ShearletUtil/helper.cpp:281: undefined reference to `ifft2(cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&, bool)'
/DATA/LivenessDectectionForFaceSpoofingAttack/src/ShearletUtil/helper.cpp:283: undefined reference to `fft2shift(cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&)'
/DATA/LivenessDectectionForFaceSpoofingAttack/src/ShearletUtil/helper.cpp:320: undefined reference to `fft2(cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&, bool)'
collect2: error: ld returned 1 exit status
Makefile:94: recipe for target '../bin/lbp' failed
make: *** [../bin/lbp] Error 1

Do you encounter this to ? Any idea to resolve it ?

Cordialy
Olivier Jouve

**Comment by Eudian** [comment]
@olijouve I have encountered the some problem.
 To workaround I move helper.cpp and shear.cpp from ShearletUtil to src directory,
and add shear.pp to _SHEARLET_ADDON in Makefile.

**Comment by gc535** [comment]
I am sorry but you are right. There were some path and building issues that I haven't got time to fix back then, but I think it's a easy fix.  Since Xeudien got it working, I will close this issue now.
